# Generated by Django 4.2.4 on 2023-09-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_scope_delete_articles_to_tags_alter_article_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scope',
            new_name='tags',
        ),
    ]
