# Generated by Django 4.2.4 on 2023-09-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_temp', models.FloatField(verbose_name='Измеренная температура')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата-время измерения')),
                ('sens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sens', to='measurement.sensor')),
            ],
        ),
    ]
