# Generated by Django 4.2.4 on 2023-09-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
